### ISSUE TITLE
Dreaded sprite trash is visible

### ISSUE THREAD

**Issue by grahambates** [grahambates/desire-fm#1]
@MK1Roxxor thanks for flagging this issue on Pouet. I couldn't find your email so I've tagged you here.

I'm possibly overlooking something, but I'm not seeing this in FS-UAE or my real A500. Could you point me in the direction of where this happens, and on what configuration?

I just checked back over the code and don't see anything obviously wrong. Some parts enable sprite DMA, but then I always disable it when switching parts, after a `WaitEOF` to hopefully ensure it happens in the vblank.

I really appreciate your help on this.

**Comment by grahambates** [comment]
I figured it out. My null sprite data wasn't in Chip RAM 🤦.
Strangly I was only able to reproduce the issue in the vAmiga web emulator.

**Comment by MK1Roxxor** [comment]
That very likely caused the issue. I will check the new version of the intro on my A500 and report back to you if the problems are fixed. For future conversations you can use the following (slightly encrypted) mail address: my user name on pouet+_dsd+@+gmx.de.
